version: '3.2'
services:
  env:
    image: python:alpine
    ports:
      - 80:5000
    volumes:
      - ./app/.:/usr/src/myapp
    working_dir: /usr/src/myapp
    command: sh -c "pip install Flask && python home.py"
    
