version: '3.8'
services:
  server:
    build: ./flask/.
    ports:
      - 80:5000
    volumes:
      - ./app/.:/usr/src/myapp
    working_dir: /usr/src/myapp
    # command: sh -c "python database.py"
    command: sh -c "flask --app app run --host='0.0.0.0'" 
  database:
    build: ./mysql/.
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d:ro
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
